# Generated by Django 3.2.18 on 2023-05-24 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True, verbose_name='اسم الأول')),
                ('second_name', models.CharField(max_length=100, null=True, verbose_name='اسم الأب')),
                ('last_name', models.CharField(max_length=100, null=True, verbose_name='اللقب')),
                ('serial', models.CharField(default='ABC', max_length=120, null=True, unique=True, verbose_name='الرقم التسلسلي')),
                ('gender', models.CharField(choices=[(0, 'ذكر'), (1, 'أنثى')], max_length=100, verbose_name='الجنس')),
                ('date_of_birth', models.CharField(max_length=100, null=True, verbose_name='تاريخ ميلاد الطفل')),
            ],
        ),
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_number', models.PositiveIntegerField(verbose_name='رقم الجرع')),
                ('production_date', models.CharField(max_length=100, null=True, verbose_name='تاريخ الإنتاج')),
                ('exp_date', models.CharField(max_length=100, null=True, verbose_name='تاريخ الإنتهاء')),
                ('for_age', models.CharField(max_length=100, null=True, verbose_name='لعمر')),
            ],
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المحافظة')),
            ],
            options={
                'verbose_name': 'محافظة',
                'verbose_name_plural': 'المحافظات',
            },
        ),
        migrations.CreateModel(
            name='Serum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم اللقاح')),
                ('type', models.CharField(default=0, max_length=100, verbose_name='نوع اللقاح')),
                ('made_in', models.CharField(max_length=100, null=True, verbose_name='بلد المنشأ')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.CharField(max_length=100, null=True, verbose_name='تاريخ الزيارة')),
                ('is_taken', models.BooleanField(default=False)),
                ('next_visit', models.PositiveIntegerField(null=True, verbose_name='الزيارة القادمة بعد')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dozes.child', verbose_name='الطفل')),
                ('dose', models.ManyToManyField(to='dozes.Dose', verbose_name='الجرع')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend_text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dozes_recommends',
            },
        ),
        migrations.AddField(
            model_name='dose',
            name='serum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dozes.serum', verbose_name='اللقاح'),
        ),
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المديرية')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dozes.governorate', verbose_name='المحافظة')),
            ],
            options={
                'verbose_name': 'مديرية',
                'verbose_name_plural': 'المديريات',
            },
        ),
        migrations.AddField(
            model_name='child',
            name='directorate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dozes.directorate', verbose_name='المديرية'),
        ),
    ]
