# Generated by Django 3.2.18 on 2023-05-24 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dozes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='phone',
            field=models.CharField(max_length=9, null=True, verbose_name='رقم الجوال'),
        ),
        migrations.AddField(
            model_name='child',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
