# Generated by Django 4.2 on 2023-05-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dozes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[(0, 'ذكر'), (1, 'أنثى')], max_length=100, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='dose',
            name='for_age',
            field=models.CharField(default=0, max_length=100, null=True, verbose_name='لعمر'),
        ),
        migrations.AlterField(
            model_name='serum',
            name='type',
            field=models.CharField(default=0, max_length=100, verbose_name='نوع اللقاح'),
        ),
    ]
