# Generated by Django 3.2.18 on 2023-05-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dozes', '0002_auto_20230525_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], max_length=100, verbose_name='الجنس'),
        ),
    ]
