# Generated by Django 3.2.18 on 2023-05-07 21:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dozes', '0005_alter_dose_production_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommends',
            new_name='Recommendations',
        ),
        migrations.AlterModelTable(
            name='recommendations',
            table='dozes_recommends',
        ),
    ]
