# Generated by Django 3.2.18 on 2023-04-13 20:18

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dozes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المحافظة')),
            ],
            options={
                'verbose_name': 'محافظة',
                'verbose_name_plural': 'المحافظات',
            },
        ),
        migrations.RemoveField(
            model_name='child',
            name='name',
        ),
        migrations.AddField(
            model_name='child',
            name='first_name',
            field=models.CharField(max_length=100, null=True, verbose_name='اسم الأول'),
        ),
        migrations.AddField(
            model_name='child',
            name='gender',
            field=models.IntegerField(choices=[(0, 'ذكر'), (1, 'أنثى')], default=0, verbose_name='الجنس'),
        ),
        migrations.AddField(
            model_name='child',
            name='last_name',
            field=models.CharField(max_length=100, null=True, verbose_name='اللقب'),
        ),
        migrations.AddField(
            model_name='child',
            name='second_name',
            field=models.CharField(max_length=100, null=True, verbose_name='اسم الأب'),
        ),
        migrations.AddField(
            model_name='child',
            name='serial',
            field=models.CharField(default='ABC', max_length=120, null=True, unique=True, verbose_name='الرقم التسلسلي'),
        ),
        migrations.AddField(
            model_name='dose',
            name='exp_date',
            field=models.DateField(null=True, verbose_name='تاريخ الإنتهاء'),
        ),
        migrations.AddField(
            model_name='dose',
            name='for_age',
            field=models.IntegerField(choices=[(0, 'شراب'), (1, 'حقنة'), (2, 'كبسولة')], default=0, null=True, verbose_name='لعمر'),
        ),
        migrations.AddField(
            model_name='dose',
            name='production_date',
            field=models.DateField(null=True, verbose_name='تاريخ الإنتاج'),
        ),
        migrations.AddField(
            model_name='serum',
            name='made_in',
            field=django_countries.fields.CountryField(max_length=2, null=True, verbose_name='بلد المنشأ'),
        ),
        migrations.AddField(
            model_name='serum',
            name='type',
            field=models.IntegerField(choices=[(0, 'شراب'), (1, 'حقنة'), (2, 'كبسولة')], default=0, verbose_name='نوع اللقاح'),
        ),
        migrations.AddField(
            model_name='visit',
            name='next_visit',
            field=models.PositiveIntegerField(null=True, verbose_name='الزيارة القادمة بعد'),
        ),
        migrations.AlterField(
            model_name='child',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='تاريخ ميلاد الطفل'),
        ),
        migrations.AlterField(
            model_name='dose',
            name='dose_number',
            field=models.PositiveIntegerField(verbose_name='رقم الجرع'),
        ),
        migrations.AlterField(
            model_name='dose',
            name='serum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dozes.serum', verbose_name='اللقاح'),
        ),
        migrations.AlterField(
            model_name='serum',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم اللقاح'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dozes.child', verbose_name='الطفل'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='dose',
            field=models.ManyToManyField(to='dozes.Dose', verbose_name='الجرع'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(auto_now=True, verbose_name='تاريخ الزيارة'),
        ),
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المديرية')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dozes.governorate', verbose_name='المحافظة')),
            ],
            options={
                'verbose_name': 'مديرية',
                'verbose_name_plural': 'المديريات',
            },
        ),
        migrations.AddField(
            model_name='child',
            name='directorate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dozes.directorate', verbose_name='المديرية'),
        ),
    ]
