# Generated by Django 3.2.18 on 2023-04-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dozes', '0002_auto_20230413_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
