# Generated by Django 4.2 on 2023-05-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dozes', '0002_alter_child_gender_alter_dose_for_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dose',
            name='for_age',
            field=models.CharField(max_length=100, null=True, verbose_name='لعمر'),
        ),
    ]
