# Generated by Django 4.2 on 2023-05-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dozes', '0003_alter_dose_for_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dose',
            name='production_date',
            field=models.CharField(max_length=100, verbose_name='تاريخ الإنتاج'),
        ),
    ]
